### ISSUE TITLE
Finish elemental analysis protocol

### ISSUE THREAD

**Issue by dschwilk** [schwilklab/protocols#12]
Rough start is here: https://github.com/schwilklab/protocols/blob/master/elemental_analysis.md

**Comment by efwaring** [comment]
An FYI, I talked with Dr. Lee. I had some issues with some of my heavier samples for elemental analysis.  Closer to 1 mg is best.  Might want to consider changing the range to 0.75 to 1.5 mg.

**Comment by dschwilk** [comment]
I'm closing this issue.  I assume this is all good: https://github.com/schwilklab/protocols/blob/master/methods/elemental_analysis.md
