### ISSUE TITLE
Need leaf protein extraction protocol

### ISSUE THREAD

**Issue by dschwilk** [schwilklab/protocols#13]
Let's get this written down as well.

**Comment by dschwilk** [comment]
Hi @efwaring . Can we get citation and link to a reference in this protocol?

**Comment by efwaring** [comment]
@dschwilk I added in the citation and some more info on this protocol.  Are the data entry sheets made by L. Plata on github anywhere so I can link to them?

**Comment by dschwilk** [comment]
@efwaring Thanks so much! I checked and I never received anything else from lplata.  If you think this looks ok as is you can close the issue.

**Comment by efwaring** [comment]
all information that needs to be recorded has been added. This issue is closed
