### ISSUE TITLE
storage and care of Li-6400

### ISSUE THREAD

**Issue by efwaring** [schwilklab/protocols#17]
Create a protocol on HOW to prep the licor for storage with details on WHY this important to maintaining the machines

**Comment by dschwilk** [comment]
How about a single licor6400 document with sections on 

- training requirements
- links to training materials
- prep checklist
- measurement checklist
- storage, etc.

**Comment by efwaring** [comment]
Good idea. I will combine all those into one protocol with sections.

**Comment by dschwilk** [comment]
Bumping this. Also the current licor document should be made into a markdown document for nicer formatting on screen and printing.

**Comment by efwaring** [comment]
Has been updated to a markdown file. Need to consult with Jennifer Smith on what has changed with newest software update

**Comment by efwaring** [comment]
Have updated all besides test.  Will be putting test in its own file.  This issue is closed
